//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reviewer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reviewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}일 후과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sAfterDateFolderAdd {
            get {
                return ResourceManager.GetString("sAfterDateFolderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCANCEL {
            get {
                return ResourceManager.GetString("sCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 복습을 마쳤습니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCongraturation {
            get {
                return ResourceManager.GetString("sCongraturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열에 중복된 값이 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDateStringDuplicated {
            get {
                return ResourceManager.GetString("sDateStringDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용된 날짜가 없습니다. 복습 안하실 건가요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDateStringEmpty {
            get {
                return ResourceManager.GetString("sDateStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열을 형식에 맞게 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDateStringError {
            get {
                return ResourceManager.GetString("sDateStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDefaultState {
            get {
                return ResourceManager.GetString("sDefaultState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로 설정이 잘 못 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sERROR_WRONG_PATH {
            get {
                return ResourceManager.GetString("sERROR_WRONG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _{0}일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFixedDateForderAdd {
            get {
                return ResourceManager.GetString("sFixedDateForderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더를 설정해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFolderDefaultWord {
            get {
                return ResourceManager.GetString("sFolderDefaultWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFolderName_Finish {
            get {
                return ResourceManager.GetString("sFolderName_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFolderName_Log {
            get {
                return ResourceManager.GetString("sFolderName_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFolderName_Start {
            get {
                return ResourceManager.GetString("sFolderName_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복습에 체크된 항목이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sNoCheckList_InReviewList {
            get {
                return ResourceManager.GetString("sNoCheckList_InReviewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복습할 항목이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sNoList_InReviewList {
            get {
                return ResourceManager.GetString("sNoList_InReviewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복습할 파일이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sNoReviewFiles {
            get {
                return ResourceManager.GetString("sNoReviewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sOK {
            get {
                return ResourceManager.GetString("sOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reviewer 바로가기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sShortcutExe {
            get {
                return ResourceManager.GetString("sShortcutExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공부폴더 바로가기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sShortcutStartReview {
            get {
                return ResourceManager.GetString("sShortcutStartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잠시만 기다려 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sWaitState {
            get {
                return ResourceManager.GetString("sWaitState", resourceCulture);
            }
        }
    }
}
