//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reviewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reviewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일 후.
        /// </summary>
        public static string sAfterDateFolderAdd {
            get {
                return ResourceManager.GetString("sAfterDateFolderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string sCANCEL {
            get {
                return ResourceManager.GetString("sCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오늘 모든 복습을 마쳤습니다!.
        /// </summary>
        public static string sCongraturation_FinishDailyReview {
            get {
                return ResourceManager.GetString("sCongraturation_FinishDailyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 축하합니다! {0} 파일의 긴 복습의 기간을 마쳤습니다!.
        /// </summary>
        public static string sCongraturation_FinishReviewFile {
            get {
                return ResourceManager.GetString("sCongraturation_FinishReviewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문자열에 중복된 값이 있습니다..
        /// </summary>
        public static string sDateStringDuplicated {
            get {
                return ResourceManager.GetString("sDateStringDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용된 날짜가 없습니다. 복습 안하실 건가요?.
        /// </summary>
        public static string sDateStringEmpty {
            get {
                return ResourceManager.GetString("sDateStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문자열을 형식에 맞게 다시 입력해 주세요..
        /// </summary>
        public static string sDateStringError {
            get {
                return ResourceManager.GetString("sDateStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경로 설정이 잘 못 되었습니다..
        /// </summary>
        public static string sERROR_WRONG_PATH {
            get {
                return ResourceManager.GetString("sERROR_WRONG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=tGykPqgKB4I&amp;t.
        /// </summary>
        public static string sExplainYotubeURL {
            get {
                return ResourceManager.GetString("sExplainYotubeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}일.
        /// </summary>
        public static string sFixedDateFoderAdd_UI {
            get {
                return ResourceManager.GetString("sFixedDateFoderAdd_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _{0}일.
        /// </summary>
        public static string sFixedDateForderAdd {
            get {
                return ResourceManager.GetString("sFixedDateForderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더를 설정해 주세요..
        /// </summary>
        public static string sFolderDefaultWord {
            get {
                return ResourceManager.GetString("sFolderDefaultWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string sFolderName_Finish {
            get {
                return ResourceManager.GetString("sFolderName_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string sFolderName_Start {
            get {
                return ResourceManager.GetString("sFolderName_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string sFolderName_Study {
            get {
                return ResourceManager.GetString("sFolderName_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습한 항목이 없습니다..
        /// </summary>
        public static string sNoCheckList_InReviewList {
            get {
                return ResourceManager.GetString("sNoCheckList_InReviewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습할 항목이 없습니다..
        /// </summary>
        public static string sNoList_InReviewList {
            get {
                return ResourceManager.GetString("sNoList_InReviewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습할 파일이 없습니다..
        /// </summary>
        public static string sNoReviewFiles {
            get {
                return ResourceManager.GetString("sNoReviewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더를 먼저 선택해주세요..
        /// </summary>
        public static string sNoReviewFolder {
            get {
                return ResourceManager.GetString("sNoReviewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : 파일 이름이 형식에 맞지 않습니다..
        /// </summary>
        public static string sNotMatchedFileName {
            get {
                return ResourceManager.GetString("sNotMatchedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string sOK {
            get {
                return ResourceManager.GetString("sOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=tGykPqgKB4I&amp;t.
        /// </summary>
        public static string sOriginYoutubeURL {
            get {
                return ResourceManager.GetString("sOriginYoutubeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습할 파일을 선택해주세요..
        /// </summary>
        public static string sReviewSelectFile {
            get {
                return ResourceManager.GetString("sReviewSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습할 파일은 하나만 선택해 주세요..
        /// </summary>
        public static string sReviewSelectMuchFile {
            get {
                return ResourceManager.GetString("sReviewSelectMuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer 바로가기.
        /// </summary>
        public static string sShortcutExe {
            get {
                return ResourceManager.GetString("sShortcutExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공부폴더 바로가기.
        /// </summary>
        public static string sShortcutStartReview {
            get {
                return ResourceManager.GetString("sShortcutStartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string sState_Default {
            get {
                return ResourceManager.GetString("sState_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복습 파일 실행..
        /// </summary>
        public static string sState_FileExecute {
            get {
                return ResourceManager.GetString("sState_FileExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잠시만 기다려 주세요..
        /// </summary>
        public static string sState_Wait {
            get {
                return ResourceManager.GetString("sState_Wait", resourceCulture);
            }
        }
    }
}
